approvals:
 #you can check for a special approval pattern
 pattern: "^(approved|:\\+1:|👍)$"
 minimum: 1
 # ignore: pr_opener
 
 veto:
  pattern: "^(:\\-1:|👎)$"
 
 from:
  users: 
   - milkmaaan
   - Nyuikoshe
 
 #groups:
  #these have their own full approval sub-structure
  #w/ minimum, from, etc.
